### ISSUE TITLE
Some Error with Unity

### ISSUE THREAD

**Issue by LegoZeng** [krasing/DRLearningContinuousControl#1]
When I run the code as README, the problem comes:
env = UnityEnvironment(file_name='Reacher_Linux/Reacher.x86_64')
The environment does not need user interaction to launch
	 The Academy and the External Brain(s) are attached to objects in the Scene
	 The environment and the Python interface have compatible versions.

**Comment by krasing** [comment]
I can't understand what is the problem. Just switch to the notebook with Alt+Tab and continue execution of the cells.
